spring.application.name=nhonApp
server.port=8081
## H2 Database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

# Database configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/nhon
spring.datasource.username=user
spring.datasource.password=thanhnhan
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.cloud.compatibility-verifier.enabled=false


# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Settings
jwt.secret=your-super-secret-key-that-is-long-and-secure
jwt.expiration=86400000


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.example.nhonApp.controller


spring.redis.host=localhost
spring.redis.port=6379

api.openweathermap.key=N9RJWJURDVLYRTUVEDMQS8FM3

# Keycloak Configuration
keycloak.realm=nhonapp-realm
keycloak.auth-server-url=http://localhost:8080
#keycloak.ssl-required=external
keycloak.resource=nhonapp-backend
#keycloak.credentials.secret=your-client-secret
#keycloak.use-resource-role-mappings=true
keycloak.bearer-only=true

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/nhonapp-realm
