spring.application.name=nhonApp
server.port=8081
## H2 Database configuration
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

# Database configuration
spring.datasource.url=jdbc:mariadb://localhost:3306/nhon
spring.datasource.username=user
spring.datasource.password=thanhnhan
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
spring.sql.init.mode=always
spring.cloud.compatibility-verifier.enabled=false


# JPA/Hibernate properties
spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Settings
jwt.secret=your-super-secret-key-that-is-long-and-secure
jwt.expiration=86400000


springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.packages-to-scan=com.example.nhonApp.controller

springdoc.oidc.discovery.url=http://localhost:8080/realms/nhonapp-realm/.well-known/openid-configuration
springdoc.swagger-ui.oauth.client-id=nhonapp-client
springdoc.swagger-ui.oauth.client-secret=${keycloak.client-secret}


spring.redis.host=localhost
spring.redis.port=6379

api.openweathermap.key=N9RJWJURDVLYRTUVEDMQS8FM3

# realm Configuration
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/nhonapp-realm

# Keycloak client Configuration
keycloak.realm=nhonapp-realm
keycloak.client-id=nhonapp-client
keycloak.client-secret=I13yHpWlyYNYIm6i82GYfyrpKb1SI6TM
keycloak.token-uri=http://localhost:8080/realms/${keycloak.realm}/protocol/openid-connect/token

keycloak.server-url=http://localhost:8080
keycloak.admin.url=http://localhost:8080/admin/realms/${keycloak.realm}

# Kafka Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=my-group
#
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#spring.kafka.consumer.group-id=book-service-group
#
#spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.trusted.packages=*

spring.messages.basename=i18n/messages
